# Generated by Django 4.1.2 on 2022-10-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_paring_dish_pairing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='protien',
            new_name='protein',
        ),
    ]
