# Generated by Django 4.1.2 on 2022-10-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_protien_dish_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine',
            field=models.CharField(choices=[('R', 'Red Wine'), ('W', 'White Wine'), ('S', 'Sparkling Wine'), ('D', 'Dessert Wine')], default='R', max_length=1),
        ),
    ]
